/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion.widgets;

import javax.swing.JSlider;

/**
 *
 * @author Oswaldo
 */
public class WCoordenadaPunto extends javax.swing.JPanel {

    /**
     * Creates new form CoordenadaPunto
     */
    public WCoordenadaPunto() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlX = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        sliX = new javax.swing.JSlider();
        pnlY = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        sliY = new javax.swing.JSlider();

        setLayout(new java.awt.GridLayout(2, 0));

        pnlX.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("X:");
        jLabel1.setToolTipText("");
        jLabel1.setMinimumSize(new java.awt.Dimension(30, 80));
        pnlX.add(jLabel1, java.awt.BorderLayout.WEST);

        sliX.setMajorTickSpacing(500);
        sliX.setMaximum(2000);
        sliX.setMinorTickSpacing(1);
        sliX.setPaintLabels(true);
        sliX.setPaintTicks(true);
        sliX.setName("x"); // NOI18N
        pnlX.add(sliX, java.awt.BorderLayout.CENTER);

        add(pnlX);

        pnlY.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Y:");
        jLabel2.setMinimumSize(new java.awt.Dimension(30, 80));
        pnlY.add(jLabel2, java.awt.BorderLayout.WEST);

        sliY.setMajorTickSpacing(500);
        sliY.setMaximum(2000);
        sliY.setMinorTickSpacing(1);
        sliY.setPaintLabels(true);
        sliY.setPaintTicks(true);
        sliY.setName("y"); // NOI18N
        pnlY.add(sliY, java.awt.BorderLayout.CENTER);

        add(pnlY);
    }// </editor-fold>//GEN-END:initComponents

    public void setName(String name){
        super.setName(name);
        sliX.setName((getName()!=null?name+",":"")+"x");
        sliY.setName((getName()!=null?name+",":"")+"y");
    }
    
    public JSlider getSliX() {
        return sliX;
    }

    public JSlider getSliY() {
        return sliY;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel pnlX;
    private javax.swing.JPanel pnlY;
    private javax.swing.JSlider sliX;
    private javax.swing.JSlider sliY;
    // End of variables declaration//GEN-END:variables
}
