
package presentacion;

import java.awt.BorderLayout;
import java.awt.Canvas;
import java.awt.Component;
import java.awt.Container;
import javax.swing.JComboBox;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JTextField;
import presentacion.widgets.WCoordenadaPunto;


public class Vista extends javax.swing.JFrame {

    private Controlador control;
    private Modelo modelo;

    public Vista(Modelo m) {
        modelo = m;
        initComponents();
        componentesPersonales();
        asignacionEventos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlTriangulos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbListaTriangulos = new javax.swing.JComboBox<>();
        pnlPuntos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlPuntoA = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnlPuntoB = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnlPuntoC = new javax.swing.JPanel();
        pnlDatos = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtperimetro = new javax.swing.JTextField();
        txtDistanciaAB = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDistanciaAC = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDistanciaBC = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtArea = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mniCrear = new javax.swing.JMenuItem();
        mniEliminar = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mniSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 410));
        getContentPane().setLayout(new java.awt.BorderLayout(5, 5));

        pnlTriangulos.setMinimumSize(new java.awt.Dimension(200, 50));

        jLabel1.setText("Seleccione el triángulo:");

        cmbListaTriangulos.setMinimumSize(new java.awt.Dimension(80, 26));

        javax.swing.GroupLayout pnlTriangulosLayout = new javax.swing.GroupLayout(pnlTriangulos);
        pnlTriangulos.setLayout(pnlTriangulosLayout);
        pnlTriangulosLayout.setHorizontalGroup(
            pnlTriangulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTriangulosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbListaTriangulos, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlTriangulosLayout.setVerticalGroup(
            pnlTriangulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTriangulosLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(cmbListaTriangulos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(pnlTriangulos, java.awt.BorderLayout.NORTH);

        pnlPuntos.setBorder(javax.swing.BorderFactory.createTitledBorder("Coordenadas de los vertices"));
        pnlPuntos.setAutoscrolls(true);
        pnlPuntos.setMinimumSize(new java.awt.Dimension(407, 200));
        pnlPuntos.setPreferredSize(new java.awt.Dimension(450, 200));
        pnlPuntos.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("A");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipady = 40;
        pnlPuntos.add(jLabel2, gridBagConstraints);

        pnlPuntoA.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 18;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 320;
        gridBagConstraints.insets = new java.awt.Insets(9, 9, 9, 9);
        pnlPuntos.add(pnlPuntoA, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("B");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 40;
        pnlPuntos.add(jLabel3, gridBagConstraints);

        pnlPuntoB.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 18;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 320;
        gridBagConstraints.insets = new java.awt.Insets(9, 9, 9, 9);
        pnlPuntos.add(pnlPuntoB, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("C");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 40;
        pnlPuntos.add(jLabel4, gridBagConstraints);

        pnlPuntoC.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 18;
        gridBagConstraints.ipadx = 320;
        gridBagConstraints.insets = new java.awt.Insets(9, 9, 9, 9);
        pnlPuntos.add(pnlPuntoC, gridBagConstraints);

        getContentPane().add(pnlPuntos, java.awt.BorderLayout.WEST);
        pnlPuntos.getAccessibleContext().setAccessibleDescription("");

        pnlDatos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnlDatos.setMinimumSize(new java.awt.Dimension(200, 200));
        pnlDatos.setPreferredSize(new java.awt.Dimension(300, 200));
        pnlDatos.setLayout(null);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Perímetro ");
        jLabel5.setMaximumSize(new java.awt.Dimension(500, 30));
        jLabel5.setMinimumSize(new java.awt.Dimension(80, 30));
        jLabel5.setPreferredSize(new java.awt.Dimension(80, 30));
        pnlDatos.add(jLabel5);
        jLabel5.setBounds(10, 30, 280, 30);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Distancia A-B");
        jLabel6.setMaximumSize(new java.awt.Dimension(500, 30));
        jLabel6.setMinimumSize(new java.awt.Dimension(80, 30));
        jLabel6.setPreferredSize(new java.awt.Dimension(80, 30));
        pnlDatos.add(jLabel6);
        jLabel6.setBounds(10, 100, 280, 30);

        txtperimetro.setEditable(false);
        txtperimetro.setBackground(new java.awt.Color(255, 255, 255));
        txtperimetro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtperimetro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtperimetro.setMaximumSize(new java.awt.Dimension(500, 30));
        txtperimetro.setMinimumSize(new java.awt.Dimension(80, 30));
        txtperimetro.setPreferredSize(new java.awt.Dimension(80, 30));
        pnlDatos.add(txtperimetro);
        txtperimetro.setBounds(10, 60, 280, 30);

        txtDistanciaAB.setEditable(false);
        txtDistanciaAB.setBackground(new java.awt.Color(255, 255, 255));
        txtDistanciaAB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDistanciaAB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDistanciaAB.setMaximumSize(new java.awt.Dimension(500, 30));
        txtDistanciaAB.setMinimumSize(new java.awt.Dimension(80, 30));
        txtDistanciaAB.setPreferredSize(new java.awt.Dimension(80, 30));
        pnlDatos.add(txtDistanciaAB);
        txtDistanciaAB.setBounds(10, 130, 280, 30);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Distancia A-C");
        jLabel7.setMaximumSize(new java.awt.Dimension(500, 30));
        jLabel7.setMinimumSize(new java.awt.Dimension(80, 30));
        jLabel7.setPreferredSize(new java.awt.Dimension(80, 30));
        pnlDatos.add(jLabel7);
        jLabel7.setBounds(10, 180, 280, 30);

        txtDistanciaAC.setEditable(false);
        txtDistanciaAC.setBackground(new java.awt.Color(255, 255, 255));
        txtDistanciaAC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDistanciaAC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDistanciaAC.setMaximumSize(new java.awt.Dimension(500, 30));
        txtDistanciaAC.setMinimumSize(new java.awt.Dimension(80, 30));
        txtDistanciaAC.setPreferredSize(new java.awt.Dimension(80, 30));
        pnlDatos.add(txtDistanciaAC);
        txtDistanciaAC.setBounds(10, 210, 280, 30);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Distancia B-C");
        jLabel8.setMaximumSize(new java.awt.Dimension(500, 30));
        jLabel8.setMinimumSize(new java.awt.Dimension(80, 30));
        jLabel8.setPreferredSize(new java.awt.Dimension(80, 30));
        pnlDatos.add(jLabel8);
        jLabel8.setBounds(10, 260, 280, 30);

        txtDistanciaBC.setEditable(false);
        txtDistanciaBC.setBackground(new java.awt.Color(255, 255, 255));
        txtDistanciaBC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDistanciaBC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDistanciaBC.setMaximumSize(new java.awt.Dimension(500, 30));
        txtDistanciaBC.setMinimumSize(new java.awt.Dimension(80, 30));
        txtDistanciaBC.setPreferredSize(new java.awt.Dimension(80, 30));
        pnlDatos.add(txtDistanciaBC);
        txtDistanciaBC.setBounds(10, 290, 280, 30);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Area");
        jLabel9.setMaximumSize(new java.awt.Dimension(500, 30));
        jLabel9.setMinimumSize(new java.awt.Dimension(80, 30));
        jLabel9.setPreferredSize(new java.awt.Dimension(80, 30));
        pnlDatos.add(jLabel9);
        jLabel9.setBounds(10, 340, 280, 30);

        txtArea.setEditable(false);
        txtArea.setBackground(new java.awt.Color(255, 255, 255));
        txtArea.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtArea.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtArea.setMaximumSize(new java.awt.Dimension(500, 30));
        txtArea.setMinimumSize(new java.awt.Dimension(80, 30));
        txtArea.setPreferredSize(new java.awt.Dimension(80, 30));
        pnlDatos.add(txtArea);
        txtArea.setBounds(10, 370, 280, 30);

        getContentPane().add(pnlDatos, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Opciones");

        mniCrear.setText("Crear triángulo");
        jMenu1.add(mniCrear);

        mniEliminar.setText("Eliminar triángulo");
        jMenu1.add(mniEliminar);
        jMenu1.add(jSeparator2);

        mniSalir.setText("Salir");
        jMenu1.add(mniSalir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public Controlador getControl() {
        if(control == null){
            control = new Controlador(this);
        }
        return control;
    }
    
    public Modelo getModelo() {
        return modelo;
    }

    public JMenuItem getMniCrear() {
        return mniCrear;
    }

    public JMenuItem getMniEliminar() {
        return mniEliminar;
    }

    public JMenuItem getMniSalir() {
        return mniSalir;
    }

    public JComboBox<String> getCmbListaTriangulos() {
        return cmbListaTriangulos;
    }

    public JTextField getTxtArea() {
        return txtArea;
    }

    public JTextField getTxtDistanciaAB() {
        return txtDistanciaAB;
    }

    public JTextField getTxtDistanciaAC() {
        return txtDistanciaAC;
    }

    public JTextField getTxtDistanciaBC() {
        return txtDistanciaBC;
    }

    public JTextField getTxtPerimetro() {
        return txtperimetro;
    }

    public WCoordenadaPunto[] getWPuntoCoord() {
        return puntoCoord;
    }

    public JPanel getPnlPuntos() {
        return pnlPuntos;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbListaTriangulos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem mniCrear;
    private javax.swing.JMenuItem mniEliminar;
    private javax.swing.JMenuItem mniSalir;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlPuntoA;
    private javax.swing.JPanel pnlPuntoB;
    private javax.swing.JPanel pnlPuntoC;
    private javax.swing.JPanel pnlPuntos;
    private javax.swing.JPanel pnlTriangulos;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtDistanciaAB;
    private javax.swing.JTextField txtDistanciaAC;
    private javax.swing.JTextField txtDistanciaBC;
    private javax.swing.JTextField txtperimetro;
    // End of variables declaration//GEN-END:variables

    private WCoordenadaPunto puntoCoord[];
    
    private void componentesPersonales() {
        puntoCoord = new WCoordenadaPunto[3];
        for (int i = 0; i < 3; i++) {
            puntoCoord[i] = new WCoordenadaPunto();
            puntoCoord[i].setName(""+i);
        }
        
        pnlPuntoA.add(puntoCoord[0], BorderLayout.CENTER);
        pnlPuntoB.add(puntoCoord[1], BorderLayout.CENTER);
        pnlPuntoC.add(puntoCoord[2], BorderLayout.CENTER);
        
    }

    private void asignacionEventos() {
        mniCrear.addActionListener(getControl());
        mniEliminar.addActionListener(getControl());
        mniSalir.addActionListener(getControl());
        cmbListaTriangulos.addItemListener(getControl());
        for (int i = 0; i < 3; i++) {
            puntoCoord[i].getSliX().addChangeListener(getControl());
            puntoCoord[i].getSliY().addChangeListener(getControl());
        }
    }
    
    public void activarComponentes(Container c, boolean enable) {
        Component[] componentes = c.getComponents();
        for (Component componente : componentes) {
            componente.setEnabled(enable);
            if (componente instanceof Container) {
                activarComponentes((Container)componente, enable);
            }
        }
    } 
    
    public void reset(boolean estado){
        getMniEliminar().setEnabled(!estado);
        activarComponentes(getPnlPuntos(), !estado);
        
        if(estado){
            Component[] componentesDatos = pnlDatos.getComponents();
            for (Component c : componentesDatos) {            
                if (c instanceof JTextField) {
                    ((JTextField) c).setText("");
                }
            }
            Component[] componentesPuntos = pnlPuntos.getComponents();
            for (Component c : componentesPuntos) {            
                if (c instanceof JPanel) {
                    JPanel pnlCoord = (JPanel)c;
                    Component[] componentesCoordenada = pnlCoord.getComponents();
                    for (Component coor : componentesCoordenada) {
                        if (coor instanceof WCoordenadaPunto) {
                            ((WCoordenadaPunto) coor).getSliX().setValue(0);
                            ((WCoordenadaPunto) coor).getSliY().setValue(0);
                        }
                    }
                }
            }
        }
    }
}
